apiVersion: batch/v1
kind: Job
metadata:
  name: ping-google-job
spec:
  template:
    spec:
      containers:
      - name: ping-container
        image: busybox
        command: ["ping"]
        args: ["-c", "4", "google.com"]
      restartPolicy: Never
